site_name: Dagger DSL
repo_name: Dagger DSL
site_description: "Dagger DSL. Kotlin Symbol Processing"
site_author: Butov Anton.

site_url: https://antonbutov.github.io/dagger-dsl/
repo_url: https://github.com/AntonButov/dagger-dsl

theme:
  name: material
  favicon: images/dsl.png
  icon:
    logo: material/library
  palette:
    # Light theme (default)
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark theme
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'index.md'