name: Changelog Generator

# Conventional Commits Types:
# - feat:     New feature for the user
# - fix:      Bug fix
# - docs:     Changes to documentation
# - style:    Formatting, missing semi colons, etc
# - refactor: Refactoring production code
# - test:     Adding tests, refactoring test
# - chore:    Updating build tasks, package manager configs, etc

on:
  push:
    branches:
      - trunk

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          version=$(grep "^version =" gradle/libs.versions.toml | cut -d'"' -f2)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"
          tag-prefix: 'v'
          version: ${{ steps.get_version.outputs.VERSION }}

      - name: Create Git Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Delete existing tag if it exists
          git tag -d v${{ steps.get_version.outputs.VERSION }} || true
          git push origin :refs/tags/v${{ steps.get_version.outputs.VERSION }} || true
          
          # Create new tag
          git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release v${{ steps.get_version.outputs.VERSION }}"
          git push origin v${{ steps.get_version.outputs.VERSION }}
          git-push: false  # Prevent automatic pushing of tags
